name: Ley

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: main
        path: main
    - uses: actions/checkout@v2
      with:
        ref: pages
        path: pages
    - name: Install Rust Nightly
      uses: actions-rs/toolchain@v1
      with:
          profile: minimal
          toolchain: nightly
          override: true
    - name: Install Ley
      run: cargo install ley
    - name: Build Ley Files
      run: ley --index --style '/blog.css' main/src/ pages/
    - name: Commit Changes
      run: |
          cd pages
          git config user.name "Ley Builder"
          git config user.email "aidop@me.com"
          git add "*.html"
          git commit -m "Auto-built Ley files"
          git push
      continue-on-error: true
    - name: Notify Pages Repo
      uses: actions/github-script@v3
      with:
        github-token: ${{secrets.REPO_DISPATCH_TOKEN}}
        script: |
            github.repos.createDispatchEvent({owner: "AidoP", repo: "AidoP.github.io", event_type: "blog"})
