name: Ley

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: git fetch origin pages
    - name: Install Rust Nightly
      uses: actions-rs/toolchain@v1
      with:
          profile: minimal
          toolchain: nightly
          override: true
    - name: Install Ley
      run: cargo install ley
    - name: Build Ley Files
      run: ley src/
    - name: Save changes
      run: git add '*.html' && git stash
    - name: Show what is going on
      run: git status
    - name: Change branch to pages
      run: git checkout pages
    - name: Remove old pages
      run: rm *.html
    - name: Restore Changes
      run: git stash pop
    - name: Upload Built Ley
      uses: EndBug/add-and-commit@v5
      with:
        add: '*.html'
        author_name: 'Ley Builder'
        branch: pages
        message: 'Automatically built Ley files'
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
