name: Ley

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Rust Nightly
      uses: actions-rs/toolchain@v1
      with:
          profile: minimal
          toolchain: nightly
          override: true
    - name: Install Ley
      run: cargo install ley
    - name: Build Ley Files
      run: ley src/
    - name: Move to pages branch
      uses: actions/checkout@v2
      with:
        ref: pages
    - name: Upload Built Ley
      uses: EndBug/add-and-commit@v5
      with:
        add: '*.html'
        author_name: 'Ley Builder'
        branch: pages
        message: 'Automatically built Ley files'
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
