name: Ley

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: git fetch origin pages
    - name: Install Rust Nightly
      uses: actions-rs/toolchain@v1
      with:
          profile: minimal
          toolchain: nightly
          override: true
    - name: Install Ley
      run: cargo install ley
    - name: Build Ley Files
      run: ley src/
    - name: Save changes
      run: git add '*.html' && git stash
    - name: Show what is going on
      run: git status
    - name: Change branch to pages
      run: git checkout pages
    - name: Revert to first base pages commit
      run: git reset --hard 545bca0
    - name: Restore Changes
      run: git stash pop
    - name: Set git credentials
      run: |
          git config user.name 'Ley Builder'
          git config user.email 'aidop@me.com'
          git commit -m "Automatically built Ley files"
          git push
