name: Notify Update
on:
  push:
    branches: [ pages ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Trigger Event
        uses: actions/github-script@v3.0.0
        with:
          script: |
              github.actions.createWorkflowDispatch({owner: "AidoP", repo: "AidoP.github.io", workflow_id: "update.yml", ref: "master"})
