name: Notify

on:
  push:
    branches: [pages]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Notify Pages Repo
        uses: actions/github-script@v3
        with:
          github-token: ${{secrets.REPO_DISPATCH_TOKEN}}
          script: |
              github.repos.createDispatchEvent({owner: "AidoP", repo: "AidoP.github.io", event_type: "blog"})
