name: Notify Update
on:
  push:
    branches: [ pages ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Trigger Event
        uses: actions/github-script@v3.0.0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            await github.request('POST /repos/{owner}/{repo}/dispatches', {
              owner: 'AidoP',
              repo: 'AidoP.github.io',
              event_type: 'blog'
            })
